name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in the repository  # Passo para depuração
        run: ls -R  # Isso irá listar todos os arquivos no repositório

      - name: Replace placeholders in main.js
        run: |
          sed -i "s|API_KEY_PLACEHOLDER|${{ secrets.FIREBASE_API_KEY }}|g" ./main.js
          sed -i "s|AUTH_DOMAIN_PLACEHOLDER|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" ./main.js
          sed -i "s|PROJECT_ID_PLACEHOLDER|${{ secrets.FIREBASE_PROJECT_ID }}|g" ./main.js
          sed -i "s|STORAGE_BUCKET_PLACEHOLDER|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" ./main.js
          sed -i "s|MESSAGING_SENDER_ID_PLACEHOLDER|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" ./main.js
          sed -i "s|APP_ID_PLACEHOLDER|${{ secrets.FIREBASE_APP_ID }}|g" ./main.js
          sed -i "s|MEASUREMENT_ID_PLACEHOLDER|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" ./main.js
          sed -i "s|DATABASE_URL_PLACEHOLDER|${{ secrets.FIREBASE_DATABASE_URL }}|g" ./main.js

      - name: Install dependencies
        run: |
          npm install  # Instalar as dependências do npm, se necessário

      - name: Build your project
        run: |
          npm run build  # ou o comando correspondente ao seu projeto

      - name: Deploy (opcional)
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
