name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Replace placeholders in main.js
        run: |
          # Substituir os placeholders pelas variáveis de ambiente
          sed -i "s|API_KEY_PLACEHOLDER|${{ secrets.FIREBASE_API_KEY }}|g" src/main.js
          sed -i "s|AUTH_DOMAIN_PLACEHOLDER|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" src/main.js
          sed -i "s|PROJECT_ID_PLACEHOLDER|${{ secrets.FIREBASE_PROJECT_ID }}|g" src/main.js
          sed -i "s|STORAGE_BUCKET_PLACEHOLDER|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" src/main.js
          sed -i "s|MESSAGING_SENDER_ID_PLACEHOLDER|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" src/main.js
          sed -i "s|APP_ID_PLACEHOLDER|${{ secrets.FIREBASE_APP_ID }}|g" src/main.js
          sed -i "s|MEASUREMENT_ID_PLACEHOLDER|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" src/main.js
          sed -i "s|DATABASE_URL_PLACEHOLDER|${{ secrets.FIREBASE_DATABASE_URL }}|g" src/main.js

      - name: Build your project (if needed)
        run: |
          # Com seu código já com as variáveis injetadas, você pode rodar o build aqui
          npm run build  # ou o comando correspondente ao seu projeto

      - name: Deploy (opcional)
        run: |
          # Opcional, caso você queira fazer o deploy após o build
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
